_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 41
                - 50
                - 55
            "2":
                - 1
                - 41
                - 50
                - 55
            "3":
                - 2
                - 14
                - 16
                - 17
                - 23
                - 55
            "4": 3.10.13
            "5": 0.19.2
            "8":
                - 5
            "12": 0.19.2
            "13": darwin-arm64
batch_size:
    value: 32
data:
    value:
        name: FashionMNIST
        num_classes: 10
experiment:
    value:
        epochs: 1
lr:
    value: 0.001
paths:
    value:
        processed_dir: ./data/processed
        raw_dir: ./data/raw
        save_dir: models/
