steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build api container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west10-docker.pkg.dev/fashion-mnist-448314/docker-registry/gcp_apiv2_fmnist',
    '-f',
    'dockerfiles/api.dockerfile'
  ]
  env:
    - 'DOCKER_BUILDKIT=1'
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push api container image'
  args: [
    'push',
    'europe-west10-docker.pkg.dev/fashion-mnist-448314/docker-registry/gcp_apiv2_fmnist'
  ]
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy api to Cloud Run'
  args: [
    'run',
    'deploy',
    'gcp-api-fmnist',
    '--image',
    'europe-west1-docker.pkg.dev/fashion-mnist-448314/docker-registry/gcp_apiv2_fmnist',
    '--region',
    'europe-west1',
    '--platform',
    'managed'
  ]
options:
  logging: CLOUD_LOGGING_ONLY
