defaults:
  - _self_  
  
hydra:
  run:
    dir: .

# Training Configuration
experiment:
  epochs: 1
  
data:
  name: FashionMNIST
  num_classes : 10

paths:
  raw_dir : "./data/raw"
  processed_dir : "./data/processed"
  save_dir: models/